#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER";

    create table if not exists users(
      user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_name varchar not null
    );

    create table if not exists tasks(
      task_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title varchar not null,
      description varchar not null,
      deadline DATE not null,
      task_type varchar not null,
      owner_id bigint,
      CONSTRAINT fk_user
        FOREIGN KEY(owner_id)
          REFERENCES users(user_id)
    );
EOSQL