CREATE TABLE if NOT EXISTS users
(
    user_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR,
    middle_name VARCHAR,
    last_name   VARCHAR,
    email       VARCHAR,
    password    VARCHAR
);



CREATE TABLE if NOT EXISTS projects
(
    project_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_title       VARCHAR NOT NULL,
    project_description VARCHAR NOT NULL
);



CREATE TABLE if NOT EXISTS users_projects
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_of_user    INTEGER,
    CONSTRAINT fk_user
        FOREIGN KEY (id_of_user)
            REFERENCES users (user_id),

    id_of_project INTEGER,
    CONSTRAINT fk_project
        FOREIGN KEY (id_of_project)
            REFERENCES projects (project_id)
);



CREATE TABLE if NOT EXISTS tasks
(
    task_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_title       VARCHAR NOT NULL,
    task_description VARCHAR NOT NULL,
    deadline         DATE    NOT NULL,
    task_type        varchar NOT NULL,
    id_of_user       INTEGER,
    CONSTRAINT fk_user
        FOREIGN KEY (id_of_user)
            REFERENCES users (user_id),
    id_of_project    INTEGER,
    CONSTRAINT fk_project
        FOREIGN KEY (id_of_project)
            REFERENCES projects (project_id)
);



CREATE TABLE if NOT EXISTS comments
(
    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR NOT NULL,
    id_of_task INTEGER,
    CONSTRAINT fk_task
        FOREIGN KEY (id_of_task)
            REFERENCES tasks (task_id)
);
