CREATE TABLE if NOT EXISTS users
(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL
);

CREATE TABLE if NOT EXISTS tasks
(
    task_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_title       VARCHAR NOT NULL,
    task_description VARCHAR NOT NULL,
    deadline         DATE    NOT NULL,
    task_type        varchar NOT NULL,
    id_of_user       INTEGER,
    CONSTRAINT fk_user
        FOREIGN KEY (id_of_user)
            REFERENCES users (user_id)
                ON DELETE CASCADE
);