CREATE TABLE if NOT EXISTS users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR NOT NULL
);

CREATE TABLE if NOT EXISTS tasks(
    task_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    deadline DATE NOT NULL,
    task_type varchar NOT NULL,
    owner_id INTEGER,
    CONSTRAINT fk_user
        FOREIGN KEY(owner_id)
            REFERENCES users(user_id)
);