ALTER TABLE IF EXISTS users
    ADD middle_name VARCHAR,
    ADD last_name   VARCHAR,
    ADD email       VARCHAR,
    ADD password    VARCHAR;



CREATE TABLE if NOT EXISTS projects
(
    project_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_title       VARCHAR NOT NULL,
    project_description VARCHAR NOT NULL
);


CREATE TABLE if NOT EXISTS users_projects
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_of_user    INTEGER,
    CONSTRAINT fk_user
        FOREIGN KEY (id_of_user)
            REFERENCES users (user_id)
                ON DELETE CASCADE,

    id_of_project INTEGER,
    CONSTRAINT fk_project
        FOREIGN KEY (id_of_project)
            REFERENCES projects (project_id)
                ON DELETE CASCADE
);


ALTER TABLE IF EXISTS tasks
    ADD id_of_project INTEGER,
    ADD CONSTRAINT fk_project
            FOREIGN KEY (id_of_project)
                REFERENCES projects (project_id)
                    ON DELETE CASCADE;


CREATE TABLE if NOT EXISTS comments
(
    comment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text       VARCHAR NOT NULL,
    id_of_task INTEGER,
    CONSTRAINT fk_task
        FOREIGN KEY (id_of_task)
            REFERENCES tasks (task_id)
);
